# Generated by Django 4.0.4 on 2022-04-17 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sde_sheet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('solved', models.BooleanField(default=False)),
                ('ds', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sde_sheet.dsa')),
                ('tags', models.ManyToManyField(to='sde_sheet.tags')),
            ],
        ),
    ]
