# Generated by Django 4.0.4 on 2022-04-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde_sheet', '0004_question_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='notes',
        ),
        migrations.AddField(
            model_name='dsa',
            name='notes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
